### ISSUE TITLE
A little question on reported mAP

### ISSUE THREAD

**Issue by ElectronicElephant** [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset#13]
Hello, first, thank you for the great work!

I'm just wondering what do you mean by the reported AP in your paper. Is it the traditional AP@0.5, or it's COCO-fashioned mAP@0.5:0.95?

**Comment by qqlu** [comment]
Yes, we strictly followed the COCO-fashioned mAP.

**Comment by ElectronicElephant** [comment]
OK. Thanks.
