### ISSUE TITLE
tool for annotation

### ISSUE THREAD

**Issue by quanw8781** [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset#23]
Hi @qqlu 

I have read you paper and reproduced the code.Now I want to try the work with my dataset,but I don't konw how to annotate.
Can you provide the tool for annotation or script to convert the labelme format to kins format?

Looking forward to your reply.

**Comment by Wyatt823** [comment]
请问你是怎样解决的这个问题 @quanw8781

**Comment by CHN-001** [comment]
hi，did u solve this problem？i have labelme json format and coco format，and i want convert these format to COCOA format or KINS format，thank a lot！

**Comment by CHN-001** [comment]
@quanw8781 Hello！Can u communicate with me about this question by email? I will appreciate your help very much！

**Comment by Wyatt823** [comment]
可以的，我非常愿意！


w
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月18日(星期二) 晚上6:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation (Issue #23)





 
@quanw8781 Hello！Can u communicate with me about this question by email? I will appreciate your help very much！

**Comment by CHN-001** [comment]
亲爱的王云峰朋友，我应该如何称呼你呢？我叫孙奥深，现在是华南农业大学的硕士研究生，目前做计算机视觉方向的学习，你叫我孙同学就可以的。

我来和你沟通是因为我现在存在的问题如下：我自己的数据集只有标准的COCO数据集格式，或者是labelme标注的json文件，而非COCOA格式（COCO-Amodal）。但我发现很多Amodal-Instance-Segmentation的模型需要的数据格式都是COCOA格式，而且并没有给出如何制作COCOA数据集的方法，或者是将COCO格式转换为COCOA格式的方法，这就导致我只能暂时使用支持COCO格式的模型，这让我感到非常惋惜。因此我想来和你探讨一下，你能否对我这个问题提供探讨和帮助，我将不胜感激！此外如果你方便的话能否添加你的联系方式以方便沟通？非常感谢你的来信！祝你生活愉快！


爱盖被子的夏天
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月19日(星期三) 上午10:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation (Issue #23)





 可以的，我非常愿意！ 
 
 
 w 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年6月18日(星期二) 晚上6:05 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation (Issue #23) 
 
 
 
 
 
   
 @quanw8781 Hello！Can u communicate with me about this question by email? I will appreciate your help very much！

**Comment by CHN-001** [comment]
> 可以的，我非常愿意！ w ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset" ***@***.***&gt;; 发送时间:&nbsp;2024年6月18日(星期二) 晚上6:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation (Issue #23) @quanw8781 Hello！Can u communicate with me about this question by email? I will appreciate your help very much！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

亲爱的朋友，你可以叫我孙同学，现在是华南农业大学的硕士研究生，目前做计算机视觉方向的学习。

我来和你沟通是因为我现在存在的问题如下：我自己的数据集只有标准的COCO数据集格式，或者是labelme标注的json文件，而非COCOA格式（COCO-Amodal）。但我发现很多Amodal-Instance-Segmentation的模型需要的数据格式都是COCOA格式，而且并没有给出如何制作COCOA数据集的方法，或者是将COCO格式转换为COCOA格式的方法，这就导致我只能暂时使用支持COCO格式的模型，这让我感到非常惋惜。因此我想来和你探讨一下，你能否对我这个问题提供探讨和帮助，我将不胜感激！此外如果你方便的话能否添加你的联系方式以方便沟通？非常感谢你的来信！祝你生活愉快！

**Comment by FocusGZL** [comment]
> > 可以的，我非常愿意！ w _**@**_.***  
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset" _**@**_._**>; 发送时间: 2024年6月18日(星期二) 晚上6:05 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation (Issue #23) @quanw8781 Hello！Can u communicate with me about this question by email? I will appreciate your help very much！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 亲爱的朋友，你可以叫我孙同学，现在是华南农业大学的硕士研究生，目前做计算机视觉方向的学习。
> 
> 我来和你沟通是因为我现在存在的问题如下：我自己的数据集只有标准的COCO数据集格式，或者是labelme标注的json文件，而非COCOA格式（COCO-Amodal）。但我发现很多Amodal-Instance-Segmentation的模型需要的数据格式都是COCOA格式，而且并没有给出如何制作COCOA数据集的方法，或者是将COCO格式转换为COCOA格式的方法，这就导致我只能暂时使用支持COCO格式的模型，这让我感到非常惋惜。因此我想来和你探讨一下，你能否对我这个问题提供探讨和帮助，我将不胜感激！此外如果你方便的话能否添加你的联系方式以方便沟通？非常感谢你的来信！祝你生活愉快！

我也想知道如何制作kins格式的数据集？方便邮件联系吗？不慎感激
！！！

**Comment by qqlu** [comment]
Hi All,

The KINS annotation is also in COCO format. You can visualize it in
kitti_vis_with_cocoapi.py
<https://github.com/qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset/blob/master/kitti_vis_with_cocoapi.py>
.

Thanks.

Author

ZLG ***@***.***> 于2024年7月1日周一 19:38写道：

**Comment by Wyatt823** [comment]
> > > 可以的，我非常愿意！ w _**@**_.***  [...](#) ------------------ 原始邮件 ------------------ 发件人： “qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset” _**@**_._**>; 发送时间： 2024年6月18日（星期二） 晚上6：05 _**@**_.**_>; _**@**_._**_**@**_。**_>; 主题： Re： [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset] tool for annotation （Issue #23）  您好！您可以通过电子邮件与我沟通这个问题吗？我将非常感谢您的帮助！ — 直接回复此电子邮件，在 GitHub 上查看或取消订阅。您收到此消息是因为您发表了评论。消息 ID：_**@**_。***>
> > 
> > 
> > 亲爱的朋友，你可以叫我孙同学，现在是华南农业大学的硕士研究生，目前做计算机视觉方向的学习。
> > 我来和你沟通是因为我现在存在的问题如下：我自己的数据集只有标准的COCO数据集格式，或者是labelme标注的json文件，而非COCOA格式（COCO-Amodal）。但我发现很多Amodal-Instance-Segmentation的模型需要的数据格式都是COCOA格式，而且并没有给出如何制作COCOA数据集的方法，或者是将COCO格式转换为COCOA格式的方法，这就导致我只能暂时使用支持COCO格式的模型，这让我感到非常惋惜。因此我想来和你探讨一下，你能否对我这个问题提供探讨和帮助，我将不胜感激！此外如果你方便的话能否添加你的联系方式以方便沟通？非常感谢你的来信！祝你生活愉快！
> 
> 我也想知道如何制作kins格式的数据集？方便邮件联系吗？不慎感激 !!

我也非常想跟你交流，我的微信是15006659886，真诚希望一起交流！！
