### ISSUE TITLE
COCOTools categories name spelling mistake

### ISSUE THREAD

**Issue by XianyuFFF** [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset#3]
In your 'instances_train.json' file:
cats=coco.loadCats(coco.getCatIds())
nms=[cat['name'] for cat in cats]
return 
[u'cyclist', u'pedestrian', u'car', u'tram', u'trcuk', u'van', u'misc']
'trcuk' may write be 'truck'

**Comment by qqlu** [comment]
correct
