### ISSUE TITLE
How to download the annotation file of KINS datasets?

### ISSUE THREAD

**Issue by zhixuanli** [qqlu/Amodal-Instance-Segmentation-through-KINS-Dataset#8]
How to download the annotation file of KINS datasets?

It's hard for me to find the download link after doing some search.

Could you directly show it in the README area?

Thanks a lot for your work!

**Comment by qqlu** [comment]
I have updated the README. Thanks.

**Comment by zhixuanli** [comment]
Thanks a lot!

**Comment by zhixuanli** [comment]
So actually `instances_train.json` and `instances_val.json` are the two annotation files, right?

@qqlu

**Comment by qqlu** [comment]
we follow the split of KITTI dataset, 7481 images for training and 7518
images for inference.

zhixuanli <notifications@github.com> 于2019年11月4日周一 下午3:11写道：

**Comment by zhixuanli** [comment]
Thank you!@qqlu
